IF NOT EXISTS
	(
		SELECT name FROM sys.databases
		WHERE name = N'GROCERY_STORE_INVENTORY_MANAGEMENT'
	)
BEGIN
	CREATE DATABASE [GROCERY_STORE_INVENTORY_MANAGEMENT]
END;
GO

USE [GROCERY_STORE_INVENTORY_MANAGEMENT];

IF EXISTS(SELECT TABLE_NAME 
            FROM INFORMATION_SCHEMA.TABLES
            WHERE TABLE_NAME = 'Store') ALTER TABLE [Store] DROP CONSTRAINT FK__Store__EmployeeID;
DROP TABLE IF EXISTS [SaleLineItem]
DROP TABLE IF EXISTS [Sale]
DROP TABLE IF EXISTS [Inventory]
DROP TABLE IF EXISTS [Shipment]
DROP TABLE IF EXISTS [OrderLineItem]
DROP TABLE IF EXISTS [Order]
DROP TABLE IF EXISTS [Product]
DROP TABLE IF EXISTS [Employee]
DROP TABLE IF EXISTS [Store]
DROP TABLE IF EXISTS [Customer]
DROP TABLE IF EXISTS [Person]
DROP TABLE IF EXISTS [Supplier]
DROP TABLE IF EXISTS [Address]
DROP TABLE IF EXISTS [ProductCategory]
DROP TABLE IF EXISTS [Department]


/* -------------------------- */
/*       CREATE TABLES        */
/* -------------------------- */
CREATE TABLE [Address]
(
	AddressID INT IDENTITY PRIMARY KEY NOT NULL,
	AddressLine1 VARCHAR(250) NOT NULL,
	AddressLine2 VARCHAR(250) NULL,
	City VARCHAR(100) NOT NULL,
	State VARCHAR(100) NOT NULL,
	Country VARCHAR(100) NOT NULL,
	ZipCode VARCHAR(10) NOT NULL
);

CREATE TABLE [Person]
(
	PersonID INT IDENTITY PRIMARY KEY NOT NULL,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	BirthDate DATE NULL,
	Gender VARCHAR(10) NULL,
	AddressID INT REFERENCES Address(AddressID) NULL,
	PhoneNumber VARCHAR(20) NULL,
	Email VARCHAR(100) NULL
);

CREATE TABLE [Store]
(
	StoreID INT IDENTITY PRIMARY KEY NOT NULL,
	AddressID INT REFERENCES Address(AddressID) NOT NULL,
	PhoneNumber VARCHAR(20) NOT NULL,
	ManagerEmployeeID INT NULL
);

CREATE TABLE [Customer]
(
	CustomerID INT IDENTITY PRIMARY KEY NOT NULL,
	PersonID INT REFERENCES Person(PersonID) NOT NULL,
	CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	LastSaleDate DATETIME NULL
);

CREATE TABLE [Department]
(
	DepartmentID INT IDENTITY PRIMARY KEY NOT NULL,
	DepartmentName VARCHAR(100) NOT NULL
);

CREATE TABLE [Employee]
(
	EmployeeID INT IDENTITY PRIMARY KEY NOT NULL,
	StoreID INT REFERENCES Store(StoreID) NOT NULL,
	PersonID INT REFERENCES Person(PersonID) NOT NULL,
	SSN VARCHAR(9) NOT NULL,
	Passcode VARCHAR(4) NOT NULL,
	JobTitle VARCHAR(100) NOT NULL,
	DepartmentID INT REFERENCES Department(DepartmentID) NOT NULL,
	Salary MONEY NOT NULL,
	StartDate DATE NOT NULL,
	EndDate DATE NULL
);

ALTER TABLE [Store] ADD CONSTRAINT FK__Store__EmployeeID FOREIGN KEY (ManagerEmployeeID) REFERENCES Employee(EmployeeID);

CREATE TABLE [ProductCategory]
(
	ProductCategoryID INT IDENTITY PRIMARY KEY NOT NULL,
	ProductCategoryName VARCHAR(100) NOT NULL
);

CREATE TABLE [Product]
(
	ProductID INT IDENTITY PRIMARY KEY NOT NULL,
	ProductName VARCHAR(250) NOT NULL,
	Description VARCHAR(1000) NULL,
	Brand VARCHAR(100) NULL,
	ProductCategoryID INT REFERENCES ProductCategory(ProductCategoryID) NOT NULL,
	UPC VARCHAR(50) NOT NULL,
	Weight FLOAT NULL,
	WeightUnit VARCHAR(2) NULL
);

CREATE TABLE [Inventory]
(
	StoreID INT REFERENCES Store(StoreID) NOT NULL,
	ProductID INT REFERENCES Product(ProductID) NOT NULL,
	UnitPrice MONEY NOT NULL,
	Quantity INT NOT NULL,
	ExpirationDate DATE NULL,
	PRIMARY KEY (StoreID, ProductID)
);

CREATE TABLE [Sale]
(
	SaleID INT IDENTITY PRIMARY KEY NOT NULL,
	StoreID INT REFERENCES Store(StoreID) NOT NULL,
	EmployeeID INT REFERENCES Employee(EmployeeID) NOT NULL,
	CustomerID INT REFERENCES Customer(CustomerID) NULL,
	SaleDate DATETIME NOT NULL,
	SubTotal MONEY DEFAULT 0,
	Tax MONEY DEFAULT 0,
	Total MONEY DEFAULT 0,
	ModeOfPayment VARCHAR(20) NULL
);

CREATE TABLE [SaleLineItem]
(
	SaleID INT REFERENCES Sale(SaleID) NOT NULL,
	ProductID INT REFERENCES Product(ProductID) NOT NULL,
	Quantity INT NOT NULL,
	LineItemPrice MONEY,
	PRIMARY KEY (SaleID, ProductID)
);

CREATE TABLE [Supplier]
(
	SupplierID INT IDENTITY PRIMARY KEY NOT NULL,
	SupplierName VARCHAR(250) NOT NULL,
	AddressID INT REFERENCES Address(AddressID) NOT NULL,
	PhoneNumber VARCHAR(20) NULL,
	EmailID VARCHAR(100) NULL
);

CREATE TABLE [Order]
(
	OrderID INT IDENTITY PRIMARY KEY NOT NULL,
	StoreID INT REFERENCES Store(StoreID) NOT NULL,
	OrderDate DATETIME NOT NULL,
	OrderTotal MONEY DEFAULT 0,
	ModeOfPayment VARCHAR(20) NULL,
	SupplierID INT REFERENCES Supplier(SupplierID) NOT NULL
);

CREATE TABLE [OrderLineItem]
(
	OrderID INT REFERENCES [Order](OrderID) NOT NULL,
	ProductID INT REFERENCES Product(ProductID) NOT NULL,
	Quantity INT NOT NULL,
	LineItemPrice MONEY,
	PRIMARY KEY (OrderID, ProductID)
);

CREATE TABLE [Shipment]
(
	ShipmentID INT IDENTITY PRIMARY KEY NOT NULL,
	OrderID INT REFERENCES [Order](OrderID) NOT NULL,
	DeliveryCompany VARCHAR(100) NULL,
	DeliveryDate DATETIME NULL,
	TrackingNumber VARCHAR(100) NOT NULL,
	ReceivedByEmployeeID INT REFERENCES Employee(EmployeeID) NULL
);